### ISSUE TITLE
Improve about page layout

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#195]
<img width="466" alt="2016-02-13_17_34_49_png" src="https://cloud.githubusercontent.com/assets/1269214/13029265/bae93380-d2ca-11e5-9b29-3b6e9f5e2a7e.png">

ref: SNS buttons in detail page layout.
https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/res/layout/view_speaker_sns_icons.xml#L36-L55

**Comment by shaunkawano** [comment]
Hi! This issue seems reasonable amount of work for me so I've tried to resolve it; all I did was adding `android:layout_marginBottom="@dimen/spacing_small"` to the border view above the text 'ソーシャル'; I was going to modify the margin of `@style/AboutTitle` from `8dp` to `16dp`, but it was applied to the word 'DroidKaigiについて' as well so I decided not to do so. Now the screen looks like below. Could you check it and let me know if I've missed something when you have time, @konifar ?

![device-2016-02-14-031849](https://cloud.githubusercontent.com/assets/920911/13029240/b6329346-d2c9-11e5-9d55-5086a36def9f.png)

**Comment by konifar** [comment]
@shaunkawano You might be almost correct, so feel free to sent PR :)

**Comment by shaunkawano** [comment]
:+1:

**Comment by konifar** [comment]
And I'm sorry, I update photo in description. Could you check it again?

**Comment by shaunkawano** [comment]
Yes I've checked the screenshot above and I believe that I got it right..

**Comment by konifar** [comment]
Take it easy. I'm glad and welcome any PR anytime. Thanks :smiley:

**Comment by shaunkawano** [comment]
(∩´∀｀)∩ < Glad to hear that!

**Comment by hotchemi** [comment]
I guess it's already fixed.

**Comment by shaunkawano** [comment]
@hotchemi sorry for confusion but the tap areas and the ripple effects of social icons can be better. If not reusing this issue, would it be ok to create separate issue for it?

**Comment by hotchemi** [comment]
@shaunkawano Sure! You can do that!

**Comment by shaunkawano** [comment]
@hotchemi OK! I'll create a separate issue for it then! :) Thank yoU!

**Comment by hotchemi** [comment]
:+1:
