### ISSUE TITLE
Add sponsors

### ISSUE THREAD

**Issue by KeithYokoma** [konifar/droidkaigi2016#20]

**Comment by konifar** [comment]
:eyes: 

Thanks!
Now sponsors data is in local file like below. Because I think a number of sponsor will not be changed.

```java
public static List<Sponsor> createPlatinumList() {
    List<Sponsor> list = new ArrayList<>();
    list.add(new Sponsor("https://droidkaigi.github.io/2016/images/logo/mixi.png", "https://mixi.co.jp"));
    list.add(new Sponsor("https://droidkaigi.github.io/2016/images/logo/findjob.png", "http://www.find-job.net"));
    list.add(new Sponsor("https://droidkaigi.github.io/2016/images/logo/mixiagent.png", "http://mixi-agent.jp"));
    return list;
}
```

https://github.com/konifar/droidkaigi2016/blob/master/app/src/main/java/io/github/droidkaigi/confsched/model/Sponsor.java#L17-L51

If sponsors may increase, is it better to load sponsors data from api? :)

**Comment by KeithYokoma** [comment]
It's not a big deal so that we don't need to put that data somewhere on the internet. I can add new entries in the local file. :+1:

**Comment by konifar** [comment]
@KeithYokoma OK! Thanks :+1:
