### ISSUE TITLE
Session star mark cleared after changing language setting

### ISSUE THREAD

**Issue by konifar** [konifar/droidkaigi2016#264]
1. Change language settings.
2. Reopen sessions page, session star mark are all cleared.
3. Open my schedule page and return sessions page.
4. Session star mark are all shown.

> 言語設定を変更した後の全てのセッション表示で星が表示されません。自分の参加するセッションなどに切り替えると表示されます。

**Comment by hkurokawa** [comment]
I believe, to fix this issue, we have to merge the local data and remote data. Instead of that, I think it is better to manage the My Schedule data in a separate database so that we can just clear the cache data when the language is changed.

I am afraid there is not much time to implement it before 1.1.0.
